# Dockerfile-n8n (Alpine + Python + pycryptodome)
FROM n8nio/n8n:latest

USER root

# Instalar python3, pip y pycryptodome forzando instalación
RUN apk update && \
    apk add --no-cache python3 py3-pip && \
    pip3 install --break-system-packages pycryptodome

USER node
